
// This file has been generated by the GUI designer. Do not modify.
namespace labwork
{
	public partial class cmdWindow
	{
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview2;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.HPaned hpaned7;
		
		private global::Gtk.Button button10;
		
		private global::Gtk.HPaned hpaned6;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView textview3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget labwork.cmdWindow
			this.Name = "labwork.cmdWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("cmdWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child labwork.cmdWindow.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView ();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.GtkScrolledWindow.Add (this.textview2);
			this.vbox8.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hpaned7 = new global::Gtk.HPaned ();
			this.hpaned7.CanFocus = true;
			this.hpaned7.Name = "hpaned7";
			this.hpaned7.Position = 10;
			this.hbox8.Add (this.hpaned7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hpaned7]));
			w3.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button ();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString ("Выполнить запрос!");
			this.hbox8.Add (this.button10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button10]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hpaned6 = new global::Gtk.HPaned ();
			this.hpaned6.CanFocus = true;
			this.hpaned6.Name = "hpaned6";
			this.hpaned6.Position = 10;
			this.hbox8.Add (this.hpaned6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hpaned6]));
			w5.Position = 2;
			this.vbox8.Add (this.hbox8);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox8]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView ();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.GtkScrolledWindow1.Add (this.textview3);
			this.vbox8.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.GtkScrolledWindow1]));
			w8.Position = 2;
			this.Add (this.vbox8);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button10.Clicked += new global::System.EventHandler (this.OnButton10Clicked);
		}
	}
}
