
// This file has been generated by the GUI designer. Do not modify.
namespace labwork
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Button button3;
		
		private global::Gtk.Fixed fixed20;
		
		private global::Gtk.Fixed fixed21;
		
		private global::Gtk.VPaned vpaned5;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Fixed fixed14;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Fixed fixed7;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Fixed fixed15;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry entry2;
		
		private global::Gtk.Fixed fixed8;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Fixed fixed3;
		
		private global::Gtk.Button button6;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Fixed fixed6;
		
		private global::Gtk.VPaned vpaned2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget labwork.MainWindow
			this.Name = "labwork.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 750;
			this.DefaultHeight = 750;
			// Container child labwork.MainWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.BorderWidth = ((uint)(5));
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Exit");
			this.hbox8.Add (this.button3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed20 = new global::Gtk.Fixed ();
			this.fixed20.Name = "fixed20";
			this.fixed20.HasWindow = false;
			this.hbox8.Add (this.fixed20);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed20]));
			w2.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed21 = new global::Gtk.Fixed ();
			this.fixed21.Name = "fixed21";
			this.fixed21.HasWindow = false;
			this.hbox8.Add (this.fixed21);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed21]));
			w3.Position = 2;
			this.vbox3.Add (this.hbox8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vpaned5 = new global::Gtk.VPaned ();
			this.vpaned5.CanFocus = true;
			this.vpaned5.Name = "vpaned5";
			this.vpaned5.Position = 10;
			this.vbox3.Add (this.vpaned5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vpaned5]));
			w5.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed14 = new global::Gtk.Fixed ();
			this.fixed14.Name = "fixed14";
			this.fixed14.HasWindow = false;
			this.hbox1.Add (this.fixed14);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed14]));
			w6.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Login");
			this.hbox1.Add (this.label6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label6]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.hbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
			w8.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed7 = new global::Gtk.Fixed ();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.hbox1.Add (this.fixed7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed7]));
			w9.Position = 3;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed15 = new global::Gtk.Fixed ();
			this.fixed15.Name = "fixed15";
			this.fixed15.HasWindow = false;
			this.hbox2.Add (this.fixed15);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed15]));
			w11.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Pass ");
			this.hbox2.Add (this.label7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label7]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.MaxLength = 64;
			this.entry2.InvisibleChar = '●';
			this.hbox2.Add (this.entry2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry2]));
			w13.Position = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed8 = new global::Gtk.Fixed ();
			this.fixed8.Name = "fixed8";
			this.fixed8.HasWindow = false;
			this.hbox2.Add (this.fixed8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed8]));
			w14.Position = 3;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox4.Add (this.fixed3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fixed3]));
			w16.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.BorderWidth = ((uint)(1));
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("Log In");
			this.hbox4.Add (this.button6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button6]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
			w18.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed ();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.hbox3.Add (this.fixed6);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed6]));
			w20.Position = 2;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 10;
			this.vbox3.Add (this.vpaned2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vpaned2]));
			w23.Position = 3;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.label1.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
		}
	}
}
