
// This file has been generated by the GUI designer. Do not modify.
namespace labwork
{
	public partial class addElement
	{
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.HPaned hpaned26;
		
		private global::Gtk.VPaned vpaned28;
		
		private global::Gtk.HPaned hpaned27;
		
		private global::Gtk.VPaned vpaned30;
		
		private global::Gtk.ComboBoxEntry comboboxentry7;
		
		private global::Gtk.Fixed fixed16;
		
		private global::Gtk.VPaned vpaned31;
		
		private global::Gtk.HPaned hpaned28;
		
		private global::Gtk.VPaned vpaned32;
		
		private global::Gtk.HPaned hpaned29;
		
		private global::Gtk.Button button27;
		
		private global::Gtk.VPaned vpaned21;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.HPaned hpaned20;
		
		private global::Gtk.HPaned hpaned21;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.HPaned hpaned19;
		
		private global::Gtk.HPaned hpaned22;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.HPaned hpaned18;
		
		private global::Gtk.HPaned hpaned23;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.HPaned hpaned16;
		
		private global::Gtk.HPaned hpaned17;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Entry entry9;
		
		private global::Gtk.Entry entry10;
		
		private global::Gtk.Entry entry11;
		
		private global::Gtk.Entry entry12;
		
		private global::Gtk.VPaned vpaned23;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget labwork.addElement
			this.Name = "labwork.addElement";
			this.Title = global::Mono.Unix.Catalog.GetString ("addElement");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 500;
			this.DefaultHeight = 500;
			// Container child labwork.addElement.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hpaned26 = new global::Gtk.HPaned ();
			this.hpaned26.CanFocus = true;
			this.hpaned26.Name = "hpaned26";
			this.hpaned26.Position = 10;
			// Container child hpaned26.Gtk.Paned+PanedChild
			this.vpaned28 = new global::Gtk.VPaned ();
			this.vpaned28.CanFocus = true;
			this.vpaned28.Name = "vpaned28";
			this.vpaned28.Position = 10;
			// Container child vpaned28.Gtk.Paned+PanedChild
			this.hpaned27 = new global::Gtk.HPaned ();
			this.hpaned27.CanFocus = true;
			this.hpaned27.Name = "hpaned27";
			this.hpaned27.Position = 306;
			// Container child hpaned27.Gtk.Paned+PanedChild
			this.vpaned30 = new global::Gtk.VPaned ();
			this.vpaned30.CanFocus = true;
			this.vpaned30.Name = "vpaned30";
			this.vpaned30.Position = 31;
			// Container child vpaned30.Gtk.Paned+PanedChild
			this.comboboxentry7 = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentry7.Name = "comboboxentry7";
			this.vpaned30.Add (this.comboboxentry7);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.vpaned30 [this.comboboxentry7]));
			w1.Resize = false;
			this.hpaned27.Add (this.vpaned30);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned27 [this.vpaned30]));
			w2.Resize = false;
			this.vpaned28.Add (this.hpaned27);
			this.hpaned26.Add (this.vpaned28);
			this.hbox5.Add (this.hpaned26);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hpaned26]));
			w5.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed16 = new global::Gtk.Fixed ();
			this.fixed16.Name = "fixed16";
			this.fixed16.HasWindow = false;
			this.hbox5.Add (this.fixed16);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed16]));
			w6.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vpaned31 = new global::Gtk.VPaned ();
			this.vpaned31.CanFocus = true;
			this.vpaned31.Name = "vpaned31";
			this.vpaned31.Position = 10;
			// Container child vpaned31.Gtk.Paned+PanedChild
			this.hpaned28 = new global::Gtk.HPaned ();
			this.hpaned28.CanFocus = true;
			this.hpaned28.Name = "hpaned28";
			this.hpaned28.Position = 10;
			// Container child hpaned28.Gtk.Paned+PanedChild
			this.vpaned32 = new global::Gtk.VPaned ();
			this.vpaned32.CanFocus = true;
			this.vpaned32.Name = "vpaned32";
			this.vpaned32.Position = 31;
			// Container child vpaned32.Gtk.Paned+PanedChild
			this.hpaned29 = new global::Gtk.HPaned ();
			this.hpaned29.CanFocus = true;
			this.hpaned29.Name = "hpaned29";
			this.hpaned29.Position = 143;
			// Container child hpaned29.Gtk.Paned+PanedChild
			this.button27 = new global::Gtk.Button ();
			this.button27.CanFocus = true;
			this.button27.Name = "button27";
			this.button27.UseUnderline = true;
			this.button27.Label = global::Mono.Unix.Catalog.GetString ("Добавить");
			this.hpaned29.Add (this.button27);
			global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.hpaned29 [this.button27]));
			w7.Resize = false;
			this.vpaned32.Add (this.hpaned29);
			global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.vpaned32 [this.hpaned29]));
			w8.Resize = false;
			this.hpaned28.Add (this.vpaned32);
			this.vpaned31.Add (this.hpaned28);
			this.hbox5.Add (this.vpaned31);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vpaned31]));
			w11.Position = 2;
			this.vbox6.Add (this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vpaned21 = new global::Gtk.VPaned ();
			this.vpaned21.CanFocus = true;
			this.vpaned21.Name = "vpaned21";
			this.vpaned21.Position = 10;
			this.vbox6.Add (this.vpaned21);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vpaned21]));
			w13.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hpaned20 = new global::Gtk.HPaned ();
			this.hpaned20.CanFocus = true;
			this.hpaned20.Name = "hpaned20";
			this.hpaned20.Position = 10;
			// Container child hpaned20.Gtk.Paned+PanedChild
			this.hpaned21 = new global::Gtk.HPaned ();
			this.hpaned21.CanFocus = true;
			this.hpaned21.Name = "hpaned21";
			// Container child hpaned21.Gtk.Paned+PanedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.hpaned21.Add (this.label14);
			global::Gtk.Paned.PanedChild w14 = ((global::Gtk.Paned.PanedChild)(this.hpaned21 [this.label14]));
			w14.Resize = false;
			this.hpaned20.Add (this.hpaned21);
			this.hbox8.Add (this.hpaned20);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hpaned20]));
			w16.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hpaned19 = new global::Gtk.HPaned ();
			this.hpaned19.CanFocus = true;
			this.hpaned19.Name = "hpaned19";
			this.hpaned19.Position = 10;
			// Container child hpaned19.Gtk.Paned+PanedChild
			this.hpaned22 = new global::Gtk.HPaned ();
			this.hpaned22.CanFocus = true;
			this.hpaned22.Name = "hpaned22";
			// Container child hpaned22.Gtk.Paned+PanedChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.hpaned22.Add (this.label13);
			global::Gtk.Paned.PanedChild w17 = ((global::Gtk.Paned.PanedChild)(this.hpaned22 [this.label13]));
			w17.Resize = false;
			this.hpaned19.Add (this.hpaned22);
			this.hbox8.Add (this.hpaned19);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hpaned19]));
			w19.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hpaned18 = new global::Gtk.HPaned ();
			this.hpaned18.CanFocus = true;
			this.hpaned18.Name = "hpaned18";
			this.hpaned18.Position = 10;
			// Container child hpaned18.Gtk.Paned+PanedChild
			this.hpaned23 = new global::Gtk.HPaned ();
			this.hpaned23.CanFocus = true;
			this.hpaned23.Name = "hpaned23";
			// Container child hpaned23.Gtk.Paned+PanedChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.hpaned23.Add (this.label12);
			global::Gtk.Paned.PanedChild w20 = ((global::Gtk.Paned.PanedChild)(this.hpaned23 [this.label12]));
			w20.Resize = false;
			this.hpaned18.Add (this.hpaned23);
			this.hbox8.Add (this.hpaned18);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hpaned18]));
			w22.Position = 2;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hpaned16 = new global::Gtk.HPaned ();
			this.hpaned16.CanFocus = true;
			this.hpaned16.Name = "hpaned16";
			this.hpaned16.Position = 10;
			// Container child hpaned16.Gtk.Paned+PanedChild
			this.hpaned17 = new global::Gtk.HPaned ();
			this.hpaned17.CanFocus = true;
			this.hpaned17.Name = "hpaned17";
			// Container child hpaned17.Gtk.Paned+PanedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.hpaned17.Add (this.label11);
			global::Gtk.Paned.PanedChild w23 = ((global::Gtk.Paned.PanedChild)(this.hpaned17 [this.label11]));
			w23.Resize = false;
			this.hpaned16.Add (this.hpaned17);
			this.hbox8.Add (this.hpaned16);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hpaned16]));
			w25.Position = 3;
			this.vbox6.Add (this.hbox8);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox8]));
			w26.Position = 2;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entry9 = new global::Gtk.Entry ();
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '●';
			this.hbox9.Add (this.entry9);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entry9]));
			w27.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entry10 = new global::Gtk.Entry ();
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '●';
			this.hbox9.Add (this.entry10);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entry10]));
			w28.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entry11 = new global::Gtk.Entry ();
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '●';
			this.hbox9.Add (this.entry11);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entry11]));
			w29.Position = 2;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entry12 = new global::Gtk.Entry ();
			this.entry12.CanFocus = true;
			this.entry12.Name = "entry12";
			this.entry12.IsEditable = true;
			this.entry12.InvisibleChar = '●';
			this.hbox9.Add (this.entry12);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entry12]));
			w30.Position = 3;
			this.vbox6.Add (this.hbox9);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox9]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vpaned23 = new global::Gtk.VPaned ();
			this.vpaned23.CanFocus = true;
			this.vpaned23.Name = "vpaned23";
			this.vpaned23.Position = 51;
			this.vbox6.Add (this.vpaned23);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vpaned23]));
			w32.Position = 4;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.comboboxentry7.Changed += new global::System.EventHandler (this.OnComboboxentry7Changed);
			this.button27.Clicked += new global::System.EventHandler (this.OnButton27Clicked);
		}
	}
}
